spring.application.name=SpringActuator


# Enable actuator endpoints
management.endpoints.web.exposure.include=*

# Optional (if you want to change the base path)
# management.endpoints.web.base-path=/actuator/health

# Expose specific endpoints
management.endpoints.web.exposure.include=health,info